export {default as Home} from "./Home"
export {default as Contact} from "./Contact"
export {default as Authenticate} from "./Authenticate"
export {default as Cart} from "./Cart"
export {default as Orders} from "./Orders"
export {default as Products} from "./Products"